export const ACTIONS = {
    SET_LOCATION: 'SET_LOCATION',
    TOGGLE_FULLTIME : 'TOGGLE_FULLTIME',
    SET_FILTER_BY: 'SET_FILTER_BY',
    DO_SEARCH: 'DO_SEARCH',
    IS_LOADING: 'IS_LOADING',
    IS_LOADING_NEXT_PAGE: 'IS_LOADING_NEXT_PAGE',
    SET_LAST_SEARCH : 'SET_LAST_SEARCH',
    SET_JOBS: 'SET_JOBS',
    SET_INDEXED_JOBS: 'SET_INDEXED_JOBS',
    SET_INDEXED_JOBS_NEXT_PAGE: 'SET_INDEXED_JOBS_NEXT_PAGE',
    LOAD_MORE: 'LOAD_MORE',
}